var array1 = [2,1,4,2,5,3];
var array2=array1.map((item)=>2);
console.log('arrayMap',array2)
var array3=array1.filter((item)=>item===2);
console.log('arrayFilter',array3);
var array4=array1.join('-');
console.log('arrayJoin',array4);
var array5=array1.concat(array2);
console.log('arrayConcat',array5);
var array6 = [1,2,3,4,[5,6,78]].flat();
console.log('arrayFlat',array6);
var array7 = array1.slice(1,3);
console.log('arraySlice',array7);
array1.forEach((item)=>console.log(item*2));
console.log('arrayForEach',array1);
array1.push(2);
console.log('arrayPush',array1);
array1.pop();
console.log('arrayPop',array1);
array1.shift();
console.log('arrayShift',array1);
array1.sort();
console.log('arraySort',array1);
array1.fill(0,3);
console.log('arrayFill',array1);
var array8 = [1,5,3,6,7,9];
console.log('array8',array8);
var result1 = array8.find((item)=>item===-1);
console.log('arrayFind',result1);
var result2 = array8.findIndex((item)=>item===-1);
console.log('arrayFIndIndex',result2);
var result3 = array8.indexOf("dtrt");
console.log('arrayIndiexOf',result3);
var result4 = array8.some((item)=>item==="ewrwerwe");
console.log('arraySome',result4);
var result5 = array8.every((item)=>item<=9);
console.log('arryaEvery',result5);
var result6 = array8.includes("erfrg");
console.log('arrayIncludes',result6);